/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { Entry } from './entry';

export interface Habit {
  entries?: Entry[];
  id?: number;
  metrics?: string;
  name: string;
}
